### ISSUE TITLE
Package lib/message

### ISSUE THREAD

**Issue by haxxus** [flamingYawn/discryptord#2]
Hello,  I'm new to using GO , getting this error about missing package. 
I installed Go 1.9 

root@vultr:/home/discryptord-master# go build
main.go:10:2: cannot find package "lib/message" in any of:
        /usr/local/go/src/lib/message (from $GOROOT)
        /root/Projects/Proj1/src/lib/message (from $GOPATH)

**Comment by tlip** [comment]
To be honest, this is my first go project (and the first go I’ve ever written, so this was a bit of an exploration for me too.

I assume do that adding code to the vendor folder would universally omit the need to namespace my imports under “github.com/.../etc,” but now I’m thinking that different environments might not do that (that or `go get` works different than I assumed).

I’m going to add this hotfix to my next pull request.

Sorry about that!

**Comment by tlip** [comment]
Closing because issue was fixed in b41c804.

I redownloaded the repository and it works for me. If it wasn't fixed on your end, give ma a holla'!
Thanks for bringing it to my attention!
